### ISSUE TITLE
Is it possible to provide favorite/like/rating information?

### ISSUE THREAD

**Issue by zyang1580** [THUIR/ZhihuRec-Dataset#2]
Hi, thanks for sharing such a wonderful dataset. I am very interested in making use of this dataset in my work. However, I need some extra labels such as like, collection, comment. I want to know whether it is possible to provide such labels.

**Comment by sadream** [comment]
Thanks for your support. But sorry for privacy protection, we did not save such labels of the dataset.

**Comment by zyang1580** [comment]
> Thanks for your support. But sorry for privacy protection, we did not save such labels of the dataset.
 thanks for your reply.

**Comment by zyang1580** [comment]
Thanks for your reply.
